### ISSUE TITLE
Week 8 Review - Nicole Smina

### ISSUE THREAD

**Issue by ns3539** [RyanOC526/comp-lab-class#2]
Setup: Good. All files present.

Part 1 - 2D WCA: Missing trajectories and log files for density values in between 0.5 and 1.1 (every 0.1)

Part 2 - 3D WCA: Missing trajectories and log files for density values in between 0.8 and 1.3 (every 0.1)

Inputs
sbatch script files are missing/have not been uploaded

Figures
movie.mpg is present as indicated in instructions but file name is too generic. Someone without access to instructions for this assignment wouldn’t know the scientific significance of the movie.
figures for 2D_WCA are clearly labeled, but upon opening them, they are entire VMD scripts instead of actual images
figures for 3D_WCA are not labeled clearly. there should be one density at which crystallization is observed, and then a noncrystalline image for the density below that, but your Figures directory contains images for 3 different densities. Also, like for 2D_WCA, VMD scripts were uploaded instead of the actual images

**Comment by RyanOC526** [comment]
Fixed.  Thank you! :)
